POST http://localhost:8080/exercise
Content-type: application/json

{
    "startTime": "2017-01-01 11:50",
    "durationInSeconds": 360,
    "activityType": "running"
}

###

GET http://localhost:8080/exercise

###

GET http://localhost:8080/exercise/638e64f32412272628733676